/* SimuPLC V41 - Android USB OTG no bloqueante */
#include <Arduino.h>
const uint32_t SERIAL_BAUD=115200; const uint8_t PIN_I1=2,PIN_Q1=13; const bool OUTPUT_ACTIVE_LOW=true; const uint16_t DEBOUNCE_MS=20; const uint32_t STATE_HEARTBEAT_MS=500;
enum ControlMode:uint8_t{MODE_BOTH=0,MODE_HMI=1,MODE_PHYSICAL=2}; ControlMode controlMode=MODE_BOTH,lastReportedMode=(ControlMode)255;
bool hmiI1=false,physicalI1=false,logicalI1=false,q1=false,running=true,lastRaw=false,lastReportedI1=false,lastReportedPhysical=false,lastReportedHmi=false,lastReportedQ1=false,lastReportedRunning=false;
uint32_t rawChangedAt=0,lastStateAt=0; char rxBuffer[96]; uint8_t rxLength=0; String txBuffer; uint16_t txOffset=0; bool statePending=false;
const char* modeName(){return controlMode==MODE_HMI?"HMI":controlMode==MODE_PHYSICAL?"PHYSICAL":"BOTH";}
String buildState(){String s=F("STATE,I1,");s+=(logicalI1?'1':'0');s+=F(",I1_PHYSICAL,");s+=(physicalI1?'1':'0');s+=F(",I1_HMI,");s+=(hmiI1?'1':'0');s+=F(",Q1,");s+=(q1?'1':'0');s+=F(",RUNNING,");s+=(running?'1':'0');s+=F(",CONTROL_MODE,");s+=modeName();return s;}
void queueLine(const String& line){if(txOffset<txBuffer.length()){if(line.startsWith("STATE"))statePending=true;return;}txBuffer=line;txBuffer+='\n';txOffset=0;}
void flushTx(){while(txOffset<txBuffer.length()&&Serial.availableForWrite()>0){int room=Serial.availableForWrite();if(room<=0)break;uint16_t left=(uint16_t)(txBuffer.length()-txOffset),count=(uint16_t)min((int)left,room);Serial.write((const uint8_t*)txBuffer.c_str()+txOffset,count);txOffset+=count;}if(txBuffer.length()&&txOffset>=txBuffer.length()){txBuffer="";txOffset=0;if(statePending){statePending=false;queueLine(buildState());}}}
void updatePhysical(){bool raw=digitalRead(PIN_I1)==LOW;uint32_t now=millis();if(raw!=lastRaw){lastRaw=raw;rawChangedAt=now;}if((uint32_t)(now-rawChangedAt)>=DEBOUNCE_MS)physicalI1=raw;}
void executeLogic(){logicalI1=controlMode==MODE_HMI?hmiI1:controlMode==MODE_PHYSICAL?physicalI1:(physicalI1||hmiI1);q1=running&&logicalI1;digitalWrite(PIN_Q1,q1?(OUTPUT_ACTIVE_LOW?LOW:HIGH):(OUTPUT_ACTIVE_LOW?HIGH:LOW));}
void sendState(){queueLine(buildState());lastStateAt=millis();lastReportedI1=logicalI1;lastReportedPhysical=physicalI1;lastReportedHmi=hmiI1;lastReportedQ1=q1;lastReportedRunning=running;lastReportedMode=controlMode;}
void processCommand(String cmd){cmd.trim();if(!cmd.length())return;if(cmd=="PING"){queueLine("PONG");return;}if(cmd=="GET_STATE"){updatePhysical();executeLogic();sendState();return;}if(cmd.startsWith("HELLO")){queueLine("OK,SIMUPLC,READY_V41,1");updatePhysical();executeLogic();sendState();return;}if(cmd=="RUN"||cmd=="RUN,1"){running=true;executeLogic();sendState();return;}if(cmd=="STOP"||cmd=="RUN,0"){running=false;executeLogic();sendState();return;}if(cmd.startsWith("MODE,")){String v=cmd.substring(5);v.trim();v.toUpperCase();controlMode=v=="HMI"?MODE_HMI:(v=="PHYSICAL"||v=="FISICO")?MODE_PHYSICAL:MODE_BOTH;executeLogic();sendState();return;}if(cmd.startsWith("SET,")){int p=cmd.indexOf(',',4);if(p>4){String tag=cmd.substring(4,p);tag.trim();tag.toUpperCase();if(tag=="I1")hmiI1=cmd.substring(p+1).toInt()!=0;}executeLogic();sendState();return;}queueLine("ERROR,COMANDO_NO_RECONOCIDO");}
void readCommands(){while(Serial.available()>0){char c=(char)Serial.read();if(c=='\n'){rxBuffer[rxLength]='\0';if(rxLength)processCommand(String(rxBuffer));rxLength=0;}else if(c!='\r'&&rxLength<sizeof(rxBuffer)-1)rxBuffer[rxLength++]=c;}}
void setup(){pinMode(PIN_I1,INPUT_PULLUP);pinMode(PIN_Q1,OUTPUT);digitalWrite(PIN_Q1,OUTPUT_ACTIVE_LOW?HIGH:LOW);Serial.begin(SERIAL_BAUD);txBuffer.reserve(128);rawChangedAt=millis();sendState();}
void loop(){readCommands();updatePhysical();executeLogic();flushTx();bool changed=logicalI1!=lastReportedI1||physicalI1!=lastReportedPhysical||hmiI1!=lastReportedHmi||q1!=lastReportedQ1||running!=lastReportedRunning||controlMode!=lastReportedMode;if(changed||(uint32_t)(millis()-lastStateAt)>=STATE_HEARTBEAT_MS)sendState();}
